### ISSUE TITLE
Bug after press login

### ISSUE THREAD

**Issue by Snzy027** [LachlanDev/Discord-BOT-Dashboard-V2#1]
after pressing login, it doesn't go into the home page or anything else, but stays on the login page

**Comment by LachlanDev** [comment]
Have you included a oath url in your config

**Comment by Snzy027** [comment]
Already, after auth2 it doesn't go to the home page, but still stuck on the login page

**Comment by LachlanDev** [comment]
This will have to be because of your redirect URL please ensure it is ``https://localhost:3000/login/api`` you can change localhost to either the IP of your system or domain name. Please ensure the entire URL is used.
