### ISSUE TITLE
Invalid Redirect URI

### ISSUE THREAD

**Issue by joversu** [LachlanDev/Discord-BOT-Dashboard-V2#8]
when attempting to login to the dashboard, the user is greeted with a "Invalid OAuth2 Redirect_uri". see attachment.

![image](https://user-images.githubusercontent.com/80077221/159326999-cdb7a2b9-dc29-4cfc-b047-38f76aee804c.png)

**Comment by joversu** [comment]
issue resolved.

**Comment by LiamHams** [comment]
> issue resolved.

Hi . What was the problem?I have the same issue . can you help me please?
