### ISSUE TITLE
The BAN plugin is not working.

### ISSUE THREAD

**Issue by mlordelo** [LachlanDev/Discord-BOT-Dashboard-V2#9]
The command to check if the user has permission to ban changed. Instead of `message.guild.me.hasPermission('PERMISSION')`, the current code to check it is `message.guild.me.permissions.has('PERMISSION')`.

**Comment by LachlanDev** [comment]
This will be because the BOT is still only on Discord.JS v12 I am working on a v13 update

**Comment by delicacystudios** [comment]
If it isn't working, or throws an error to the console, try to add client to the listed variables like that

```run: async (client, message, args) => {}```
